# Copyright (c) 2020 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build example - BouffaloLab

on:
  push:
    branches:
      - master
      - 'v*-branch'
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
  cancel-in-progress: true

env:
  CHIP_NO_LOG_TIMESTAMPS: true

jobs:
  bouffalolab:
    name: Bouffalo Lab

    runs-on: ubuntu-latest
    if: github.actor != 'restyled-io[bot]'

    container:
      image: ghcr.io/project-chip/chip-build-bouffalolab:181
      volumes:
        - "/tmp/bloat_reports:/tmp/bloat_reports"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Checkout submodules & Bootstrap
        uses: ./.github/actions/checkout-submodules-and-bootstrap
        with:
          platform: bouffalolab
          extra-submodule-parameters: " --recursive"
      - name: Set up environment for size reports
        uses: ./.github/actions/setup-size-reports
        if: ${{ !env.ACT }}
        with:
          gh-context: ${{ toJson(github) }}

      - name: Build example BL602 Lighting App
        run: |
          ./scripts/run_in_build_env.sh \
            "./scripts/build/build_examples.py --target bouffalolab-bl602dk-light-wifi-littlefs-mfd-rpc build"
          .environment/pigweed-venv/bin/python3 scripts/tools/memory/gh_sizes.py \
              bl602 bl602+mfd+littlefs+rpc lighting-app \
              out/bouffalolab-bl602dk-light-wifi-littlefs-mfd-rpc/chip-bl602-lighting-example.out \
              /tmp/bloat_reports/
          rm -rf ./out

      - name: Build example BL702 Lighting App (Ethernet)
        if: github.event_name != 'pull_request'
        run: |
          ./scripts/run_in_build_env.sh \
            "./scripts/build/build_examples.py --target bouffalolab-bl706dk-light-ethernet-easyflash build "
          .environment/pigweed-venv/bin/python3 scripts/tools/memory/gh_sizes.py \
              bl702 bl702+eth lighting-app \
              out/bouffalolab-bl706dk-light-ethernet-easyflash/chip-bl702-lighting-example.out \
              /tmp/bloat_reports/
          rm -rf ./out

      - name: Build example BL702 Lighting App (Wi-Fi)
        run: |
          ./scripts/run_in_build_env.sh \
            "./scripts/build/build_examples.py --target bouffalolab-bl706dk-light-wifi-littlefs-shell build "
          .environment/pigweed-venv/bin/python3 scripts/tools/memory/gh_sizes.py \
              bl702 bl702+eth lighting-app \
              out/bouffalolab-bl706dk-light-wifi-littlefs-shell/chip-bl702-lighting-example.out \
              /tmp/bloat_reports/
          rm -rf ./out

      - name: Build example BL702 Lighting App (Thread)
        run: |
          ./scripts/run_in_build_env.sh \
            "./scripts/build/build_examples.py --target bouffalolab-bl706dk-light-thread-littlefs-mfd-rpc build "
          .environment/pigweed-venv/bin/python3 scripts/tools/memory/gh_sizes.py \
              bl702 bl702+eth lighting-app \
              out/bouffalolab-bl706dk-light-thread-littlefs-mfd-rpc/chip-bl702-lighting-example.out \
              /tmp/bloat_reports/
          rm -rf ./out

      - name: Build example BL702L Lighting App
        if: github.event_name != 'pull_request'
        run: |
          ./scripts/run_in_build_env.sh \
            "./scripts/build/build_examples.py --target bouffalolab-bl704ldk-light-thread-littlefs-mfd build "
          .environment/pigweed-venv/bin/python3 scripts/tools/memory/gh_sizes.py \
              bl702l bl702l+mfd+littlefs lighting-app \
              out/bouffalolab-bl704ldk-light-thread-littlefs-mfd/chip-bl702l-lighting-example.out \
              /tmp/bloat_reports/
          rm -rf ./out

      - name: Build example BL702L Contact Sensor
        run: |
          ./scripts/run_in_build_env.sh \
            "./scripts/build/build_examples.py --target bouffalolab-bl704ldk-contact-sensor-thread-mtd-littlefs-mfd build"
          .environment/pigweed-venv/bin/python3 scripts/tools/memory/gh_sizes.py \
              bl702l bl702l+mfd+littlefs contact-sensor-app \
              out/bouffalolab-bl704ldk-contact-sensor-thread-mtd-littlefs-mfd/chip-bl702l-contact-sensor-example.out \
              /tmp/bloat_reports/
          rm -rf ./out

      - name: Build example BL616 Lighting App (Ethernet)
        if: github.event_name != 'pull_request'
        run: |
          ./scripts/run_in_build_env.sh \
            "./scripts/build/build_examples.py --target bouffalolab-bl616dk-light-ethernet-littlefs-mfd build "
          .environment/pigweed-venv/bin/python3 scripts/tools/memory/gh_sizes.py \
              bl616 bl616+ethernet lighting-app \
              out/bouffalolab-bl616dk-light-ethernet-littlefs-mfd/chip-bl616-lighting-example.out \
              /tmp/bloat_reports/
          rm -rf ./out

      - name: Build example BL616 Lighting App (Wi-Fi)
        run: |
          ./scripts/run_in_build_env.sh \
            "./scripts/build/build_examples.py --target bouffalolab-bl616dk-light-wifi-littlefs-mfd-shell build"
          .environment/pigweed-venv/bin/python3 scripts/tools/memory/gh_sizes.py \
              bl616 bl616+wifi+shell lighting-app \
              out/bouffalolab-bl616dk-light-wifi-littlefs-mfd-shell/chip-bl616-lighting-example.out \
              /tmp/bloat_reports/
          rm -rf ./out

      - name: Build example BL616 Lighting App (Thread)
        run: |
          ./scripts/run_in_build_env.sh \
            "./scripts/build/build_examples.py --target bouffalolab-bl616dk-light-thread-littlefs-mfd build"
          .environment/pigweed-venv/bin/python3 scripts/tools/memory/gh_sizes.py \
              bl616 bl616+thread lighting-app \
              out/bouffalolab-bl616dk-light-thread-littlefs-mfd/chip-bl616-lighting-example.out \
              /tmp/bloat_reports/
          rm -rf ./out

      - name: Uploading Size Reports
        uses: ./.github/actions/upload-size-reports
        if: ${{ !env.ACT }}
        with:
          platform-name: BouffaloLab
